// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: todo.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TodoClient is the client API for Todo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TodoClient interface {
	CreateTodo(ctx context.Context, in *TodoItem, opts ...grpc.CallOption) (*TodoItem, error)
	ReadTodos(ctx context.Context, in *VoidNoParam, opts ...grpc.CallOption) (*TodoItems, error)
	ReadTodosStream(ctx context.Context, in *VoidNoParam, opts ...grpc.CallOption) (Todo_ReadTodosStreamClient, error)
}

type todoClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoClient(cc grpc.ClientConnInterface) TodoClient {
	return &todoClient{cc}
}

func (c *todoClient) CreateTodo(ctx context.Context, in *TodoItem, opts ...grpc.CallOption) (*TodoItem, error) {
	out := new(TodoItem)
	err := c.cc.Invoke(ctx, "/Todo/createTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) ReadTodos(ctx context.Context, in *VoidNoParam, opts ...grpc.CallOption) (*TodoItems, error) {
	out := new(TodoItems)
	err := c.cc.Invoke(ctx, "/Todo/readTodos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) ReadTodosStream(ctx context.Context, in *VoidNoParam, opts ...grpc.CallOption) (Todo_ReadTodosStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Todo_ServiceDesc.Streams[0], "/Todo/readTodosStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &todoReadTodosStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Todo_ReadTodosStreamClient interface {
	Recv() (*TodoItem, error)
	grpc.ClientStream
}

type todoReadTodosStreamClient struct {
	grpc.ClientStream
}

func (x *todoReadTodosStreamClient) Recv() (*TodoItem, error) {
	m := new(TodoItem)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TodoServer is the server API for Todo service.
// All implementations must embed UnimplementedTodoServer
// for forward compatibility
type TodoServer interface {
	CreateTodo(context.Context, *TodoItem) (*TodoItem, error)
	ReadTodos(context.Context, *VoidNoParam) (*TodoItems, error)
	ReadTodosStream(*VoidNoParam, Todo_ReadTodosStreamServer) error
	mustEmbedUnimplementedTodoServer()
}

// UnimplementedTodoServer must be embedded to have forward compatible implementations.
type UnimplementedTodoServer struct {
}

func (UnimplementedTodoServer) CreateTodo(context.Context, *TodoItem) (*TodoItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTodo not implemented")
}
func (UnimplementedTodoServer) ReadTodos(context.Context, *VoidNoParam) (*TodoItems, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadTodos not implemented")
}
func (UnimplementedTodoServer) ReadTodosStream(*VoidNoParam, Todo_ReadTodosStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadTodosStream not implemented")
}
func (UnimplementedTodoServer) mustEmbedUnimplementedTodoServer() {}

// UnsafeTodoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TodoServer will
// result in compilation errors.
type UnsafeTodoServer interface {
	mustEmbedUnimplementedTodoServer()
}

func RegisterTodoServer(s grpc.ServiceRegistrar, srv TodoServer) {
	s.RegisterService(&Todo_ServiceDesc, srv)
}

func _Todo_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Todo/createTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).CreateTodo(ctx, req.(*TodoItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_ReadTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidNoParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).ReadTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Todo/readTodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).ReadTodos(ctx, req.(*VoidNoParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_ReadTodosStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VoidNoParam)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TodoServer).ReadTodosStream(m, &todoReadTodosStreamServer{stream})
}

type Todo_ReadTodosStreamServer interface {
	Send(*TodoItem) error
	grpc.ServerStream
}

type todoReadTodosStreamServer struct {
	grpc.ServerStream
}

func (x *todoReadTodosStreamServer) Send(m *TodoItem) error {
	return x.ServerStream.SendMsg(m)
}

// Todo_ServiceDesc is the grpc.ServiceDesc for Todo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Todo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Todo",
	HandlerType: (*TodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createTodo",
			Handler:    _Todo_CreateTodo_Handler,
		},
		{
			MethodName: "readTodos",
			Handler:    _Todo_ReadTodos_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "readTodosStream",
			Handler:       _Todo_ReadTodosStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "todo.proto",
}
